name: Build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ master ]
    paths:
    - poke-sprites-v
    - src/**
    - build.gradle
jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Setup Java 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run Gradle dist
      run: ./gradlew dist
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: entralinked
        path: build/libs/entralinked.jar
        retention-days: 7
