name: Build and Upload Artifact
on: workflow_dispatch
jobs:
  dist:
    runs-on: ubuntu-lastest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Setup Java 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run Gradle dist
      run: ./gradlew dist
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: entralinked
        path: build/libs/entralinked.jar
        retention-days: 7
